# Copyright Dit 2026
# SPDX-License-Identifier: BUSL-1.1

version: 2
registries:
  github-private:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.GO_MODULES_TOKEN }}
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    registries:
      - github-private
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
