#
# Build and test on pull request - updated to force recognition
#
name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25.1'
      - name: Configure Git for private modules
        run: git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}@github.com/".insteadOf "https://github.com/"
        env:
          GO_MODULES_TOKEN: ${{ secrets.GO_MODULES_TOKEN }}
      - name: Build
        run: go build -v ./...
        env:
          GOPRIVATE: github.com/datadatdat/*
      - name: Build command
        run: go build -o build/ssh ./cmd/ssh
        env:
          GOPRIVATE: github.com/datadatdat/*
      - name: Test
        run: go test -v ./...
        env:
          GOPRIVATE: github.com/datadatdat/*
